### ISSUE TITLE
Clash related RPC titles

### ISSUE THREAD

**Issue by DereC4** [Its-Haze/league-rpc#61]
Not sure if this was patched already or if my version is outdated, but I am getting these unhandled states for Clash related matches and loading

![image](https://github.com/user-attachments/assets/5261ad67-fe42-40dc-9c5f-d1903e965dd7)

Version 2.1.4

**Comment by Its-Haze** [comment]
Its difficult to test that the clash title works since riot does not have it available all the time. But please use the latest version and try again. v3.0.0

**Comment by DereC4** [comment]
kk
