### ISSUE TITLE
[FEATURE] Translation support

### ISSUE THREAD

**Issue by Suburbanno** [Its-Haze/league-rpc#63]
Could you add support for strings translation?

**Comment by Its-Haze** [comment]
Not sure i understand the feature request.

What language, and what strings?

**Comment by Its-Haze** [comment]
I understand that it would be nice to have the application in your native language. But I don't think this is a feature that I will be able to support. You are free to submit a pull request to add this feature if it's something you value.

Regarding the Chroma names. I can only find the names of the chromas in English. There doesn't seem to be any public data set which i can query for the chroma name in other languages other than `en-US`. Which is sad, but I can't do much about it.
